### ISSUE TITLE
data and model download links inactive

### ISSUE THREAD

**Issue by josefkr** [adrianeboyd/boyd-wnut2018#1]
Hi Adriane, 

the links to http://www.sfs.uni-tuebingen.de/~adriane/download/wnut2018/data.tar.gz 
and http://www.sfs.uni-tuebingen.de/~adriane/download/wnut2018/models.tar.gz are no longer working.

I was wondering if the data package is also available somewhere or if  you could make it accessible as part of this repo?

I'm assuming the contents of data.tar.gz archive is not just a combination of the  Falko and Merlin downloads but a processed variant.

Many thanks
Josef Ruppenhofer

**Comment by adrianeboyd** [comment]
Thanks for the note! I just added the files in github as release assets.

Not this exact topic, but I'm kind of curious about which exact spacy models were used in your recent LREC paper?
